const ActionTypes = {
  SET_SESSION: "SET_SESSION",
  DELETE_SESSION: "DELETE_SESSION",

  UPDATE_USER: "UPDATE_USER",
  
  SIDEBAR_OPEN: "SIDEBAR_OPEN",
  SIDEBAR_COLLAPSE: "SIDEBAR_COLLAPSE",
  SIDEBAR_HIDDEN: "SIDEBAR_HIDDEN",

  SHOW_SIDEBAR: "SHOW_SIDEBAR",
  HIDE_SIDEBAR: "HIDE_SIDEBAR",
  COLLAPSE_SIDEBAR: "COLLAPSE_SIDEBAR",
  UNCOLLAPSE_SIDEBAR: "UNCOLLAPSE_SIDEBAR",
};

export default ActionTypes;
